### ISSUE TITLE
openHub does not reflect current status of projects

### ISSUE THREAD

**Issue by cvvergara** [cvvergara/OSGeoLive-doc#1]
Part of the problem is that projects have broken links
Other part is that openHub does not update all the projects

tasks:
- [x] send mass mail to projects for them to verify links to the code are not broke and to have them fixed in case they are (giving 7 or 15 days or so to fix them)
- [x] wait the 7 or 15 days
- [x] send mail to open hub stating that we want all osgeo projects to be updated.
- [ ] on the mean time:
  - [ ] write a script that will parse: https://www.openhub.net/p/<project>
    - [ ] extract relevant information
    - [ ] save it in a cvs file

   

references:
https://live.osgeo.org/en/metrics.html
https://github.com/OSGeo/OSGeoLive-doc/blob/master/en/metrics.rst

**Comment by cvvergara** [comment]
Re sending an email. I suggest: 1. Send email to OSGeo-Live list, to have a public record. Then send a follow up private email using mail merge to all project contacts. Make sure your email has a question in it requiring a reply. You want to make sure that your email is received.

**Comment by camerons** [comment]
In your email, I suggest also explaining what you are planning to do, along with schedule, so they know when they need to do things by. (Basically, share the information from the proposal you have)

**Comment by cvvergara** [comment]
If going to create a new table in OpenHub, with a match between Application Id, and OpenHub metrics, you  use static text for column A instead of a formula. This is because if someone adds or deletes a line in the source list, the table will become mismatched.
