### ISSUE TITLE
Will build ing docs with DIRHTML, FR doesn't build

### ISSUE THREAD

**Issue by Bakaniko** [cvvergara/OSGeoLive-doc#24]
Command used:
`cmake -DDIRHTML=ON -DHTML=ON -DES=ON -FR=ON ..`
`make html-fr`

The english and spanish were build.

`cmake -DDIRHTML=ON -DHTML=ON -DES=ON -DFR=ON ..` doesn't work either

**Comment by cvvergara** [comment]
Testing this it looks it works ok now:

```
cd build
 rm -rf *
cmake -DDIRHTML=ON -DHTML=ON -DES=ON -DFR=ON ..
make doc
```

**Comment by cvvergara** [comment]
Generates the documentation but because its a directory structure the navigation is not correct in any language including english
(the navigation is on a theme)

Need to ask on a meeting if we are going to support the directory structure building of the documentation.
