### ISSUE TITLE
Order the images folder

### ISSUE THREAD

**Issue by Bakaniko** [cvvergara/OSGeoLive-doc#33]
All projects screenshots are  in the same folder. So actuall, all images are copied, even for the retired projects.

It will be easier to maintain (less broken links for sphinx), and lighter if retired projects images were not copied.

So for each project, a subfolder should be make with the project name:

images

|\

|  screenshots

|           \

|          1024x768

|                 |\

|                 |  52n_sos

|                 |         |\

|                 |             - 52n_sos_get_capabilities.png

|                 |             - 52n_sos_overview.png

|                 |             ...

|                 |\

|                 |  52n_wss

|                 |\ 

|                 |   IPython

...

**Comment by cvvergara** [comment]
@Bakaniko 
Made some changes
https://github.com/cvvergara/OSGeoLive-doc/tree/cm_fix_header/doc/images/projects

**Comment by Bakaniko** [comment]
Things were moved moved with commit bf3f08a072e7cc69e9ec24ad2513b61926d2fd9f and before.

Thanks Vicky :)

**Comment by Bakaniko** [comment]
Fixed in september
