### ISSUE TITLE
Remove unused images in any file of the documentation

### ISSUE THREAD

**Issue by Bakaniko** [cvvergara/OSGeoLive-doc#34]
It appears that there is images that are probably note used any more.

For example, geomoose provides:
- 7 screenshots for 2.4 release
- 14 screenshots for 2.6 release
- 14 screenshots for 2.9 release.

It is probable that 2.4 and 2.6 files are not used anymore or has to be updated with 2.9.

It is also probable that old screenshots in other projects are still in the folder.

One way to clean that is to launch sphinx and fix the errors. Sphinx will only ask for used image.

**Comment by cvvergara** [comment]
- [ ] 52nSOS
- [ ]       cesium
- [ ]     geokettle
- [ ]   geopublisher
- [ ]  gpsprune
- [ ]  ipython
- [ ]  jupyter
- [ ]    mapfish
- [ ]    mapslicer
- [ ] nc_dataset
- [ ]  openlayers
- [ ]   pgadmin
- [ ]    pywps
- [ ]     sahana
- [ ]      unknown
- [ ]         worldwindjava
- [ ] 52nWPS
- [ ]       deegree
- [ ]    geomajas
- [ ]    geoserver
- [ ]     grass
- [ ]     iris
- [ ]     kosmo
- [ ]      mapguide
- [ ]   mapwindow
- [ ]     ncWMS
- [ ]       osgeolive
- [ ]    pgrouting
- [ ]  qgis
- [ ]      spatialite
- [ ]  usb
- [ ]             zoo-project
- [ ] 52nWSS
- [ ]       desktop
- [ ]    geomoose
- [ ]    geotools
- [ ]      gvsig
- [ ]     istsos
- [ ]   leaflet
- [ ]    mapnik
- [ ]     marble
- [ ]        netcdf
- [ ]      osm_dataset
- [ ]  postgis
- [ ]    R
- [ ]         tilemill
- [ ]    ushahidi
- [ ]        zygrib
- [ ] atlasstyler
- [ ]  eoxserver
- [ ]  geonetwork
- [ ]  gmt
- [ ]           ideditor
- [ ]  josm
- [ ]     liblas
- [ ]     mapproxy
- [ ]   mb-system
- [ ]     opencpn
- [ ]     ossim
- [ ]        prune
- [ ]      rasdaman
- [ ]  tinyows
- [ ]     viking
- [ ] cartaro
- [ ]      gdal
- [ ]       geonode
- [ ]     gpsdrive
- [ ]      ipnb
- [ ]      jts
- [ ]      mapbender
- [ ]  mapserver
- [ ]  naturalearth
- [ ]  openjump
- [ ] otb
- [ ]          pycsw
- [ ]      saga
- [ ]      udig
- [ ]        virtualization

**Comment by cvvergara** [comment]
@Bakaniko 
Maybe this can be closed now.

**Comment by Bakaniko** [comment]
Nice script, very useful. 
It will be nice to have an idea of the weight gain from that cleaning.

Thanks @cvvergara

**Comment by cvvergara** [comment]
@Bakaniko 
as for the release, not much, because sphinx only use images files that finds, but for the repo, deleting garbage is always usefull :)
