### ISSUE TITLE
Add a column to distinguish osgeo project and osgeo community projects

### ISSUE THREAD

**Issue by Bakaniko** [cvvergara/OSGeoLive-doc#38]
The configuration file ,  [projects_info.csv](https://github.com/cvvergara/OSGeoLive-doc/blob/cm_fix_header/projects_info.csv), needs another column to distinguish if the project is osgeo project, or if it is osgeo community or if it is not any of those.

For osgeo project or from osgeo community, instead of the sphinx bullet, use the osgeo logo bullet based on the configuration

**Comment by cvvergara** [comment]
related to #64
