### ISSUE TITLE
Project description in overview.html

### ISSUE THREAD

**Issue by Bakaniko** [cvvergara/OSGeoLive-doc#39]
When building the docs, projects are separated by sections (desktop GIS, databases, etc).
In each section, each project has  links directing to its overview, its quickstart and eventually a short description.  

The last part is not very well know and differs between section.
- Most common case : the description  is added right after a ' - '  :+1: 
- Desktop GIS: there is no description but a ' - ' is added, which is not pretty :-1: 
- ziGryb : there is a description but it didn't appeared in last fresh build. :-1:

This needs to be investigated.

Description might be generated by this part:
 https://github.com/cvvergara/OSGeoLive-doc/blob/cm_fix_header/doc/scripts/build_overview.pl#L125

**Comment by Bakaniko** [comment]
Comment might be treated here : 

```perl
        #Writting the comment
        if(defined($values[7]) && ($values[7] !~ "")) {
            $bullets .= " - $values[7]\n";
            print "found comment: $values[7]\n";
        } else {
            $bullets .= "\n";
            print "No comment:\n";
        }
    }

```

**Comment by cvvergara** [comment]
problem was:
```
if(defined($values[7]) && ($values[7] !~ "")) {
```
to
```
if(defined($values[7]) && ($values[7] ne "")) {
```
