### ISSUE TITLE
Don't forget to remove conf.py

### ISSUE THREAD

**Issue by Bakaniko** [cvvergara/OSGeoLive-doc#41]
With the new build, the conf.py file is generated by CMake from data of [CMakeLists.txt](https://github.com/cvvergara/OSGeoLive-doc/blob/cm_fix_header/doc/CMakeLists.txt) and the [conf.py.in](https://github.com/cvvergara/OSGeoLive-doc/blob/cm_fix_header/doc/conf.py.in) template.

For now, original [conf.py](https://github.com/cvvergara/OSGeoLive-doc/blob/cm_fix_header/doc/conf.py) is kept as a reference but at the end should be removed because useless.

**Comment by cvvergara** [comment]
Once removed, rename the `conf.py.in` to `conf.py` and adjust CMakeLists
