### ISSUE TITLE
[Urgent] Fix the locale build process

### ISSUE THREAD

**Issue by Bakaniko** [cvvergara/OSGeoLive-doc#44]
* wrong command ?
    * cmake  -LOCALE=ON .. ---> cmake  -DLOCALE=ON ..
* uncorrect folders:
   * ../locale/en,ca,de,es,fr,it,ja,ko,pl,ru/ are created

See [IRC logs](http://irclogs.geoapt.com/osgeolive/%23osgeolive.2017-09-06.log)

**Comment by cvvergara** [comment]
building the pot & po files only for English
The other languages po files will be downloaded from transifex

**Comment by cvvergara** [comment]
Added a script to push to transifex only changed files

**Comment by cvvergara** [comment]
Updating the locale readme
