### ISSUE TITLE
 create a line that updates the .tx/config file in CMakeLists

### ISSUE THREAD

**Issue by Bakaniko** [cvvergara/OSGeoLive-doc#47]
Add a line that configure / update the transifex configuration during the doc building

It should look like: 
`sphinx-intl update-txconfig-resources --pot-dir locales/pot --transifex-project-name osgeolive`

Target file: [CMakeLists.txt](https://github.com/cvvergara/OSGeoLive-doc/blob/cm_fix_header/doc/CMakeLists.txt)

**Comment by cvvergara** [comment]
The commit that fixes this.

https://github.com/cvvergara/OSGeoLive-doc/commit/75413b974eb6052479a71463663d97a5d738f32f

please verify and close
