### ISSUE TITLE
images

### ISSUE THREAD

**Issue by cvvergara** [cvvergara/OSGeoLive-doc#51]
Remove dash where applicable
images/osgeo-live-logo -> images/osgeolive-logo

**Comment by bencaradocdavies** [comment]
And in file names.

**Comment by bencaradocdavies** [comment]
@cvvergara perhaps close this issue and open one in the upstream repo?

**Comment by cvvergara** [comment]
Issues are not handled in the main repo, we might need to "vote" on that

**Comment by bencaradocdavies** [comment]
Yes, we use trac for that.

**Comment by bencaradocdavies** [comment]
@cvvergara updated logos are available from this pull request:
https://github.com/OSGeo/OSGeoLive-doc/pull/339

**Comment by bencaradocdavies** [comment]
@cvvergara https://github.com/OSGeo/OSGeoLive-doc/pull/339 is been merged into master.

**Comment by cvvergara** [comment]
@bencaradocdavies 
Noticed and merged your changes into develop

Keeping this open, I will be working on checking file contents and changing where applicable.

**Comment by cvvergara** [comment]
changing my mind, I'll create a new one because this is about images
